const images = {
  pattern: require("./pattern.png"),
  profile: require("./profile.png"),
  plus: require("./plus.png"),
  arrow: require("./arrow.png"),
  avatar1: require("./avatar1.png"),
  avatar2: require("./avatar2.png"),
  avatar3: require("./avatar3.png"),
  cashback: require("./cashback.png"),
  close: require("./close.png"),
  flash: require("./flash.png"),
  logo: require("./logo.png"),
  menu: require("./menu.png"),
  money: require("./money.png"),
  more: require("./more.png"),
  movie: require("./movie.png"),
  phone: require("./phone.png"),
  plane: require("./plane.png"),
  power: require("./power.png"),
  temp: require("./temp.png"),
  scan: require("./scan.png"),
  filter: require("./filter.png"),
  facebook: require("./facebook.png"),
  google: require("./google.png"),
  apple: require("./apple.png"),
};

export default images;
